apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aistor-ui.fullname" . }}
  labels: {{- include "aistor-ui.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "aistor-ui.config" . | nindent 4 }}
---
{{- if and .Values.ca.certificates (not .Values.ca.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aistor-ui.fullname" . }}-ca
  labels: {{- include "aistor-ui.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.ca.certificates | nindent 2 }}
{{- end }}
