{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aistor-ui.fullname" . }}
  labels: {{- include "aistor-ui.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  session-key: {{ include "aistor-ui.keep" (list . "session-key" .Values.secrets.sessionKey true) | quote }}
  {{- with .Values.secrets.oidcClientSecret }}
  oidc-client-secret: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.auditWebhookSecret }}
  audit-webhook-secret: {{ . | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ include "aistor-ui.keep" (list . "redis-password" .Values.secrets.redisPassword true) | quote }}
  {{- else if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
{{- end }}
